sudo: required

services:
  - docker

before_install:
  - docker build -t patelarchana84/dockerdemo-react -f Dockerfile.dev .

script:
  - docker run -e CI=true patelarchana84/dockerdemo-react npm run test -- --coverage